## option
defaults:
  - base: forced_aligner

base:
  pretrained_model: facebook/wav2vec2-base-960h
  save_grid_path: textgrid_english
  save_script_path: data/LJSpeech
  audio_path: /code/gitRepo/data/LJSpeech-1.1/wavs
  script_path: /code/gitRepo/data/LJSpeech-1.1/metadata.csv
  normalize_option: NFC
